### ISSUE TITLE
Clustering based on Credit Card Data

### ISSUE THREAD

**Issue by ganesh-utla** [Mind-Benders/ML_DL_Projects#10]
**Problem:** Build the model which clusters the customers based on the credit card data such as purchases, credit limit, purchase frequency, balance, installment purchases, etc.

**Dataset:** https://www.kaggle.com/datasets/arjunbhasin2013/ccdata

**Comment by ganesh-utla** [comment]
@kunalagra, can you assign it to me!

**Comment by kunalagra** [comment]
Sure.
