### ISSUE TITLE
 Create a Detailed Notebook on Decision Tree Algorithm

### ISSUE THREAD

**Issue by kunalagra** [Mind-Benders/ML_DL_Projects#14]
Make a well documented notebook on Decision Tree Algorithm with at least 3 Different Datasets in Example.
Explain the theory behind this algorithm too in the Notebook (Markdown Block)

Datasets shouldn't be randomly generated. Source of Datasets used should be clearly mentioned with links

**Comment by ganesh-utla** [comment]
Hey @kunalagra, I would like to do this!

**Comment by kunalagra** [comment]
Hey @ganesh-utla . You have already been assigned one issue. Please complete it before taking new one.

**Comment by kunalagra** [comment]
Assigned @ganesh-utla as previous Issue is now closed
