### ISSUE TITLE
Regressions in Machine Learning

### ISSUE THREAD

**Issue by ganesh-utla** [Mind-Benders/ML_DL_Projects#6]
Problem: Predict the Price of the Computer based on the features such as screen, ram, etc. using the Regression models such as LinearRegression, SupportVectorRegression, DecisionTreeRegression and RandomForestRegression models.
Dataset: https://www.kaggle.com/datasets/kingburrito666/basic-computer-data-set

**Comment by ganesh-utla** [comment]
@kunalagra, can you assign it to me!

**Comment by kunalagra** [comment]
Done. Please next time use Original Reference to Dataset Link

**Comment by ganesh-utla** [comment]
Okay! I've updated the dataset link
