### ISSUE TITLE
Custom Object Detection

### ISSUE THREAD

**Issue by Adw8** [Mind-Benders/ML_DL_Projects#7]
This is a problem where we'll be using tensorflow and deep learning to detect an object of our choice in images. We'll also be using augmentation and other techniques to increase our dataset. In this project, I have used two types of Keys as our subject, and I have collected images on my own, You can use the images in the repo or you can also use freely available datasets. You will also need [LabelImg](https://github.com/heartexlabs/labelImg) to annotate the images.

**Comment by Adw8** [comment]
@kunalagra Can you assign this issue to me?

**Comment by kunalagra** [comment]
Done. 
Please Link to the Dataset (since you have collected on your own, then a repo in which your dataset is present would be fine too).

**Comment by Adw8** [comment]
yea, I'll just include the dataset within the repo, hope that's fine
